sudo: true

language: rust
rust:
  - stable

install:
  - wget https://download.libsodium.org/libsodium/releases/libsodium-1.0.12.tar.gz
  - tar -xvf libsodium-1.0.12.tar.gz
  - cd libsodium-1.0.12
  - ./configure
  - make
  - make check
  - sudo make install
