language: go

go:
  - master

install:
  - curl https://raw.githubusercontent.com/jD91mZM2/my-scripts/master/gogetbranch.sh > gogetbranch.sh
  - bash gogetbranch.sh github.com/bwmarrin/discordgo develop
  - go get github.com/bwmarrin/discordgo
  - cd PermCalc
  - go get
  - go install
  - cd -
  - go get
  - go get github.com/golang/lint/golint

script:
  - golint
  - go vet
  - go install
  - go test -race
